# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          fetch-depth: 0
          distribution: 'temurin'
          java-version: '11'
          server-id: central
          server-username: CI_DEPLOY_USERNAME # env variable for username in deploy
          server-password: CI_DEPLOY_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: CI_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install, unit test, integration test
        run: mvn install -Dmaven.javadoc.skip=true -B -V
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3        

      - name: Release to maven central
        if: github.ref_name == 'master' && github.event_name != 'pull_request' && github.repository == 'swisspost/vertx-cluster-watchdog'
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          
          chmod +x ./maybe-release.sh
          ./maybe-release.sh
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}
      - name: After release
        run: bash <(curl -s https://codecov.io/bash)
